# Generated by Django 5.2.5 on 2025-08-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcheckin',
            name='accuracy',
        ),
    ]
