# Generated by Django 5.2.5 on 2025-08-28 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('client', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='jobs.job')),
            ],
        ),
    ]
